default_context:
  project_name: 'FastAPI Vue RabbitMQ PostgreSQL Traefik full set of applications for organizing auto-dialing on Asterisk'
  project_slug: 'fastapi_full_stack'
  domain_main: 'fastapi-full-stack.com'
  domain_staging: 'stag.fastapi-full-stack.com'
  docker_swarm_stack_name_main: 'fastapi-full-stack-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-full-stack-com'
  secret_key: 'e6af52d13608f695662e9935f6d9e8c05f6ed4d37ef392b0bac5451c85a224db'
  first_superuser: 'muraigtor@gmail.com'
  first_superuser_password: 'Gfhjkm321'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://192.168.1.97", "http://192.168.1.97:4200", "http://192.168.1.97:3000", "http://192.168.1.97:8080", "https://192.168.1.97", "https://192.168.1.97:4200", "https://192.168.1.97:3000", "https://192.168.1.97:8080", "http://dev.fastapi-full-stack.com", "https://stag.fastapi-full-stack.com", "https://fastapi-full-stack.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.google.com'
  smtp_user: 'muraigtor'
  smtp_password: 'pass'
  smtp_emails_from_email: 'info@fastapi-full-stack.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'muraigtor@gmail.com'
  pgadmin_default_user_password: 'Gfhjkm321'
  traefik_constraint_tag: 'fastapi-full-stack.com'
  traefik_constraint_tag_staging: 'stag.fastapi-full-stack.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Gfhjkm321'
  sentry_dsn: ''
  docker_image_prefix: 'stack-'
  docker_image_backend: 'stack-backend'
  docker_image_celeryworker: 'stack-celeryworker'
  docker_image_frontend: 'stack-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
