[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["muraig <muranig@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7 || ^3.8 || ^3.9"
uvicorn = "^0.11.3"
fastapi = "^0.54.1"
python-multipart = "^0.0.5"
email-validator = "^1.0.5"
requests = "^2.23.0"
celery = "^4.4.2"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
tenacity = "^6.1.0"
pydantic = {extras = ["dotenv"], version = "^1.7.3"}
emails = "^0.5.15"
raven = "^6.10.0"
gunicorn = "^20.0.4"
jinja2 = "^2.11.2"
psycopg2-binary = "^2.8.5"
alembic = "^1.4.2"
sqlalchemy = "^1.3.16"
pytest = "^5.4.1"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}
aiohttp = "^3.7.3"
aiocsv = "^1.1.1"
requests-async = "^0.6.2"
voicegen = "^0.1.1"
python-dotenv = "^0.15.0"
broadcaster = "^0.2.0"
python-dateutil = "^2.8.1"
aioprocessing = "^1.1.0"
loguru = "^0.5.3"
aiologger = {extras = ["aiofiles"], version = "^0.6.0"}
python-json-logger = "^2.0.1"
httpx = "^0.17.0"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
black = "^19.10b0"
isort = "^4.3.21"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pytest = "^5.4.1"
sqlalchemy-stubs = "^0.3"
pytest-cov = "^2.8.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

