/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI Vue RabbitMQ PostgreSQL Traefik full set of applications for organizing auto-dialing on Asterisk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BodyLoginAccessTokenApiV1LoginAccessTokenPost
 */
export interface BodyLoginAccessTokenApiV1LoginAccessTokenPost {
    /**
     * 
     * @type {string}
     * @memberof BodyLoginAccessTokenApiV1LoginAccessTokenPost
     */
    grantType?: any;
    /**
     * 
     * @type {string}
     * @memberof BodyLoginAccessTokenApiV1LoginAccessTokenPost
     */
    username: any;
    /**
     * 
     * @type {string}
     * @memberof BodyLoginAccessTokenApiV1LoginAccessTokenPost
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof BodyLoginAccessTokenApiV1LoginAccessTokenPost
     */
    scope?: any;
    /**
     * 
     * @type {string}
     * @memberof BodyLoginAccessTokenApiV1LoginAccessTokenPost
     */
    clientId?: any;
    /**
     * 
     * @type {string}
     * @memberof BodyLoginAccessTokenApiV1LoginAccessTokenPost
     */
    clientSecret?: any;
}
