/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI Vue RabbitMQ PostgreSQL Traefik full set of applications for organizing auto-dialing on Asterisk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    title: any;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    id: any;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    ownerId: any;
}
