/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI Vue RabbitMQ PostgreSQL Traefik full set of applications for organizing auto-dialing on Asterisk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    email: any;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreate
     */
    isActive?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreate
     */
    isSuperuser?: any;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    fullName?: any;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    password: any;
}
